name = "shorty" # The name of your worker
main = "worker.js" # The entry point for your worker code
compatibility_date = "2023-10-30" # Use a recent compatibility date

# Routes tell Cloudflare which requests should trigger this worker.
# The worker now handles requests routed to lkly.net/+
routes = [
  { pattern = "lkly.net/+*", zone_name = "lkly.net" } # Handles API calls and redirects directly
]

# KV Namespace binding
# Make sure you create a KV namespace in your Cloudflare dashboard
# or via the command line: wrangler kv:namespace create SHORTY_LINKS
# Then, add the preview_id and id obtained from the command output below.
[[kv_namespaces]]
binding = "SHORTY_LINKS" # This is the variable name used in worker.js (env.SHORTY_LINKS)
id = "33ba4802b325423085be46e2103a1e3e" # Your Production KV namespace ID
preview_id = "" # Preview ID was not provided, leave empty for now

# Optional: Add site configuration if you plan to serve index.html via the worker directly
# [site]
# bucket = "./" # Directory containing your static assets (like index.html)
# entry-point = "." # Can be omitted if you only have worker.js
